const KEY='kryven-era-state-v3';
const P='https://images.unsplash.com/photo-';
const fallback={settings:{brand:'KRYVEN ERA',tagline:'WEAR YOUR ERA',heroTitle:'OWN THE NIGHT.',heroText:'Luxury streetwear engineered for presence.',heroVideo:'https://interactive-examples.mdn.mozilla.net/media/cc0-videos/flower.mp4',whatsapp:'7036421785',upi:'kryvenera@upi',adminPin:'KRYVEN26',currency:'₹',shipping:0,payments:{cod:true,upi:true,card:true,bank:false},deliveryNote:'Free shipping on eligible orders',supportText:'Mon–Sat · 10 AM–7 PM'},products:[{id:'KE001',name:'Kryven Era Logo Tee',category:'T-Shirts',price:1299,mrp:1999,discount:'35% OFF',rating:4.8,reviews:124,barcode:'890100000001',images:[P+'1521572163474-6864f9cf17ab?auto=format&fit=crop&w=1000&q=85'],sizes:{S:true,M:true,L:true,XL:true,XXL:false},colors:['Black','White'],description:'Oversized premium-cotton tee with a minimal metallic K mark.',features:['100% premium cotton','Oversized fit'],stock:18},{id:'KE002',name:'Kryven Signature Hoodie',category:'Hoodies',price:2499,mrp:3199,discount:'22% OFF',rating:4.7,reviews:88,barcode:'890100000002',images:[P+'1556821840-3a63f95609a7?auto=format&fit=crop&w=1000&q=85'],sizes:{S:true,M:true,L:true,XL:false,XXL:true},colors:['Black'],description:'Premium fleece hoodie with structured shoulders.',features:['480 GSM fleece','Drop shoulder'],stock:9},{id:'KE003',name:'Kryven Era Cargo Pants',category:'Pants',price:1999,mrp:2599,discount:'23% OFF',rating:4.6,reviews:67,barcode:'890100000003',images:[P+'1515886657613-9f3515b0c78f?auto=format&fit=crop&w=1000&q=85'],sizes:{S:false,M:true,L:true,XL:true,XXL:true},colors:['Black'],description:'Tapered cargo pants with utility pockets.',features:['Utility pocket system','Tapered leg'],stock:14},{id:'KE004',name:'Kryven Windcheater Jacket',category:'Jackets',price:2799,mrp:4299,discount:'35% OFF',rating:4.5,reviews:49,barcode:'890100000004',images:[P+'1551028719-00167b16eac5?auto=format&fit=crop&w=1000&q=85'],sizes:{S:true,M:true,L:true,XL:true,XXL:true},colors:['Black','Silver'],description:'Lightweight shell jacket with reflective details.',features:['Lightweight shell','Reflective trims'],stock:22},{id:'KE005',name:'Kryven Era Cap',category:'Accessories',price:999,mrp:1299,discount:'23% OFF',rating:4.4,reviews:31,barcode:'890100000005',images:[P+'1521369909029-2afed882baee?auto=format&fit=crop&w=1000&q=85'],sizes:{S:true,M:true,L:false,XL:false,XXL:false},colors:['Black','Gold'],description:'Structured 6-panel cap with embroidered K mark.',features:['Cotton twill','Structured crown'],stock:30}],cart:[],wishlist:[],profile:{},orders:[],searches:{},reviews:[]};
let state=load();let active='dashboard';
function load(){try{return JSON.parse(localStorage.getItem(KEY))||fallback}catch{return fallback}}
function save(){localStorage.setItem(KEY,JSON.stringify(state));toast('Changes saved')}
function esc(s=''){return String(s).replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'}[m]))}
function money(n){return `${state.settings.currency}${Number(n||0).toLocaleString('en-IN')}`}
function toast(t){const el=document.getElementById('toast');el.textContent=t;el.classList.add('show');setTimeout(()=>el.classList.remove('show'),2000)}
function app(){document.getElementById('adminApp').innerHTML=`<div class="admin-shell"><div class="admin-top"><div class="container admin-nav"><div class="logo"><span class="logo-mark"></span><span class="logo-text">KRYVEN ERA<small>/ ADMIN CONSOLE</small></span></div><div class="admin-actions"><a class="btn ghost" href="index.html">View store</a><button class="btn" onclick="exportData()">Export data</button></div></div></div><div id="adminBody" class="container"></div></div>`;renderBody()}
function isAuthed(){return sessionStorage.getItem('ke-admin-auth')==='1'}
function login(){document.getElementById('adminBody').innerHTML=`<div class="locked"><div class="locked-card"><div class="logo" style="justify-content:center"><span class="logo-mark"></span><span>KRYVEN ERA</span></div><h2 style="font-family:'Playfair Display',Georgia,serif">Admin access</h2><p class="muted">Only the store owner should use this console. Enter your admin PIN.</p><div class="field"><label>Admin PIN</label><input id="pin" type="password" placeholder="Enter PIN"/></div><button class="btn primary" style="width:100%;margin-top:12px" onclick="auth()">Unlock panel</button><div class="admin-note" style="margin-top:12px">Default demo PIN: KRYVEN26 · Change it in Settings.</div></div></div>`}
window.auth=()=>{if(document.getElementById('pin').value===state.settings.adminPin){sessionStorage.setItem('ke-admin-auth','1');renderBody()}else toast('Incorrect admin PIN')}
function renderBody(){if(!isAuthed()){login();return}document.getElementById('adminBody').innerHTML=`<div class="admin-layout"><aside class="side">${[['dashboard','Dashboard'],['orders','Orders'],['products','Products'],['settings','Website editor'],['payments','Payments'],['customers','Customers'],['reviews','Reviews'],['search','Search & barcode']].map(([id,t])=>`<button class="${active===id?'active':''}" onclick="go('${id}')">${t}</button>`).join('')}<button onclick="sessionStorage.removeItem('ke-admin-auth');renderBody()">Logout</button></aside><section class="admin-main">${section()}</section></div>`}
window.go=id=>{active=id;renderBody()}
function section(){switch(active){case'orders':return orders();case'products':return products();case'settings':return settings();case'payments':return payments();case'customers':return customers();case'reviews':return reviews();case'search':return searchPanel();default:return dashboard()}}
function dashboard(){const rev=state.orders.reduce((a,o)=>a+o.total,0);return `<div class="section-head"><div><div class="eyebrow">Control center</div><h2>Dashboard</h2></div><span class="chip gold">Local store data</span></div><div class="dashboard-grid"><div class="dash"><span class="muted">Orders</span><b>${state.orders.length}</b></div><div class="dash"><span class="muted">Revenue</span><b>${money(rev)}</b></div><div class="dash"><span class="muted">Customers</span><b>${state.orders.length?new Set(state.orders.map(o=>o.customer.phone)).size:0}</b></div><div class="dash"><span class="muted">Products</span><b>${state.products.length}</b></div></div><div class="form-section"><h4>How this admin works</h4><p class="admin-note">This static build stores edits/orders in the browser's localStorage. For real owner-only access and orders shared across customer devices, connect the included frontend to a backend such as Supabase/Firebase or a Vercel server/database.</p></div>`}
function orders(){return `<div class="section-head"><div><div class="eyebrow">Fulfillment</div><h2>Orders</h2></div><button class="btn" onclick="exportOrders()">Export orders CSV</button></div>${state.orders.length?`<div class="form-section"><div style="overflow:auto"><table class="table"><thead><tr><th>Order</th><th>Customer</th><th>Total</th><th>Payment</th><th>Status</th><th></th></tr></thead><tbody>${state.orders.map((o,i)=>`<tr><td><b>${esc(o.id)}</b><br><span class="muted">${new Date(o.createdAt).toLocaleString('en-IN')}</span></td><td>${esc(o.customer.name)}<br><span class="muted">${esc(o.customer.phone)}</span></td><td>${money(o.total)}</td><td>${esc(o.payment)}</td><td><span class="status ${o.status.toLowerCase()}">${esc(o.status)}</span></td><td><select onchange="setOrderStatus(${i},this.value)">${['Placed','Processing','Shipped','Out for Delivery','Delivered','Cancelled'].map(s=>`<option ${o.status===s?'selected':''}>${s}</option>`).join('')}</select></td></tr>`).join('')}</tbody></table></div></div>`:`<div class="form-section"><p class="muted">No orders yet.</p></div>`}`}
window.setOrderStatus=(i,s)=>{state.orders[i].status=s;save();renderBody()}
function products(){return `<div class="section-head"><div><div class="eyebrow">Catalog</div><h2>Products</h2></div><button class="btn primary" onclick="newProduct()">+ Add product</button></div><div style="display:grid;gap:10px">${state.products.map((p,i)=>`<div class="product-admin"><img class="preview-img" src="${p.images[0]}"><div><b>${esc(p.name)}</b><div class="muted">${esc(p.category)} · ${money(p.price)} · Barcode ${esc(p.barcode)}</div><div class="size-row">${Object.entries(p.sizes).map(([s,on])=>`<span class="size ${on?'':'off'}">${s}</span>`).join('')}</div></div><div class="admin-actions"><button class="btn" onclick="editProduct(${i})">Edit</button><button class="btn danger" onclick="deleteProduct(${i})">Delete</button></div></div>`).join('')}</div>`}
window.deleteProduct=i=>{if(confirm('Delete this product?')){state.products.splice(i,1);save();renderBody()}}
function productForm(i=null){const p=i===null?{id:'KE'+Date.now().toString().slice(-6),name:'New Kryven Product',category:'T-Shirts',price:999,mrp:1499,discount:'33% OFF',rating:5,reviews:0,barcode:'',images:['https://images.unsplash.com/photo-1521572163474-6864f9cf17ab?auto=format&fit=crop&w=1000&q=85'],sizes:{S:true,M:true,L:true,XL:true,XXL:true},colors:['Black'],description:'',features:['Premium quality','Signature Kryven fit'],stock:10}:state.products[i];
return `<div class="form-section"><h4>${i===null?'Add':'Edit'} product</h4><div class="form-grid"><div class="field"><label>Product title</label><input id="pName" value="${esc(p.name)}"></div><div class="field"><label>Category</label><input id="pCat" value="${esc(p.category)}"></div><div class="field"><label>Price</label><input id="pPrice" type="number" value="${p.price}"></div><div class="field"><label>MRP</label><input id="pMrp" type="number" value="${p.mrp}"></div><div class="field"><label>Discount label</label><input id="pDisc" value="${esc(p.discount)}"></div><div class="field"><label>Barcode / SKU</label><input id="pBarcode" value="${esc(p.barcode)}"></div><div class="field"><label>Stock</label><input id="pStock" type="number" value="${p.stock}"></div><div class="field"><label>Colours (comma separated)</label><input id="pColors" value="${esc(p.colors.join(', '))}"></div><div class="field" style="grid-column:1/-1"><label>Image URLs (one per line)</label><textarea id="pImages">${esc(p.images.join('\n'))}</textarea></div><div class="field" style="grid-column:1/-1"><label>Description</label><textarea id="pDesc">${esc(p.description)}</textarea></div><div class="field" style="grid-column:1/-1"><label>Features (one per line)</label><textarea id="pFeatures">${esc(p.features.join('\n'))}</textarea></div></div><div class="detail-label">Sizes available</div><div class="chips">${['S','M','L','XL','XXL'].map(s=>`<label class="chip"><input id="size_${s}" type="checkbox" ${p.sizes[s]?'checked':''}> ${s}</label>`).join('')}</div><div class="admin-actions" style="margin-top:15px"><button class="btn primary" onclick="saveProduct(${i===null?'null':i})">Save product</button><button class="btn" onclick="go('products')">Cancel</button></div></div>`}
window.newProduct=()=>{active='products';document.querySelector('.admin-main').innerHTML=productForm()}
window.editProduct=i=>{active='products';document.querySelector('.admin-main').innerHTML=productForm(i)}
window.saveProduct=i=>{const p={id:i===null?`KE${Date.now().toString().slice(-6)}`:state.products[i].id,name:document.getElementById('pName').value,category:document.getElementById('pCat').value,price:Number(document.getElementById('pPrice').value),mrp:Number(document.getElementById('pMrp').value),discount:document.getElementById('pDisc').value,barcode:document.getElementById('pBarcode').value,stock:Number(document.getElementById('pStock').value),colors:document.getElementById('pColors').value.split(',').map(x=>x.trim()).filter(Boolean),images:document.getElementById('pImages').value.split('\n').map(x=>x.trim()).filter(Boolean),description:document.getElementById('pDesc').value,features:document.getElementById('pFeatures').value.split('\n').map(x=>x.trim()).filter(Boolean),rating:i===null?5:state.products[i].rating,reviews:i===null?0:state.products[i].reviews,sizes:Object.fromEntries(['S','M','L','XL','XXL'].map(s=>[s,document.getElementById('size_'+s).checked]))};if(i===null)state.products.unshift(p);else state.products[i]=p;save();renderBody()}
function settings(){const s=state.settings;return `<div class="section-head"><div><div class="eyebrow">Storefront</div><h2>Website editor</h2></div><button class="btn primary" onclick="saveSettings()">Save website</button></div><div class="form-section"><h4>Brand & landing page</h4><div class="form-grid"><div class="field"><label>Brand name</label><input id="sBrand" value="${esc(s.brand)}"></div><div class="field"><label>Tagline</label><input id="sTag" value="${esc(s.tagline)}"></div><div class="field"><label>Hero title</label><input id="sHeroTitle" value="${esc(s.heroTitle)}"></div><div class="field"><label>Hero video URL</label><input id="sVideo" value="${esc(s.heroVideo)}"></div><div class="field" style="grid-column:1/-1"><label>Hero text</label><textarea id="sHeroText">${esc(s.heroText)}</textarea></div></div><p class="admin-note">Temporary demo video is already set. Replace it with your own MP4 URL or hosted video file URL. Static Vercel pages cannot permanently store browser-uploaded media without storage/backend.</p></div><div class="form-section"><h4>Support & contact</h4><div class="form-grid"><div class="field"><label>WhatsApp number</label><input id="sWa" value="${esc(s.whatsapp)}"></div><div class="field"><label>UPI ID</label><input id="sUpi" value="${esc(s.upi)}"></div><div class="field"><label>Shipping charge</label><input id="sShip" type="number" value="${s.shipping}"></div><div class="field"><label>Support hours</label><input id="sHours" value="${esc(s.supportText)}"></div></div></div><div class="form-section"><h4>Admin security</h4><div class="form-grid"><div class="field"><label>Admin PIN</label><input id="sPin" value="${esc(s.adminPin)}"></div></div><p class="admin-note">This PIN protects this browser's admin screen only. For real owner-only access, use a server-side auth system.</p></div>`}
window.saveSettings=()=>{const s=state.settings;s.brand=document.getElementById('sBrand').value;s.tagline=document.getElementById('sTag').value;s.heroTitle=document.getElementById('sHeroTitle').value;s.heroVideo=document.getElementById('sVideo').value;s.heroText=document.getElementById('sHeroText').value;s.whatsapp=document.getElementById('sWa').value;s.upi=document.getElementById('sUpi').value;s.shipping=Number(document.getElementById('sShip').value||0);s.supportText=document.getElementById('sHours').value;s.adminPin=document.getElementById('sPin').value;save();}
function payments(){const p=state.settings.payments;return `<div class="section-head"><div><div class="eyebrow">Checkout</div><h2>Payment methods</h2></div><button class="btn primary" onclick="savePayments()">Save payment settings</button></div><div class="form-section"><h4>Enable / disable methods</h4>${[['cod','Cash on Delivery'],['upi','UPI payment'],['card','Credit / Debit Card'],['bank','Net Banking']].map(([k,t])=>`<div class="toggle-row"><span>${t}</span><label class="switch"><input id="pay_${k}" type="checkbox" ${p[k]?'checked':''}><span class="slider"></span></label></div>`).join('')}<p class="admin-note" style="margin-top:12px">The front-end checkout updates automatically. Actual card/UPI collection requires your payment gateway credentials or a server-side payment provider.</p></div>`}
window.savePayments=()=>{for(const k of ['cod','upi','card','bank'])state.settings.payments[k]=document.getElementById('pay_'+k).checked;save()}
function customers(){const map={};state.orders.forEach(o=>{const key=o.customer.phone||o.customer.email||o.customer.name;map[key]=o.customer});const vals=Object.values(map);return `<div class="section-head"><div><div class="eyebrow">Customer data</div><h2>Customers</h2></div></div><div class="form-section"><div style="overflow:auto"><table class="table"><thead><tr><th>Name</th><th>Phone</th><th>City</th><th>Address</th></tr></thead><tbody>${vals.map(c=>`<tr><td>${esc(c.name)}</td><td>${esc(c.phone)}</td><td>${esc(c.city)}</td><td>${esc(c.address)}</td></tr>`).join('')||'<tr><td colspan="4" class="muted">No customer orders yet.</td></tr>'}</tbody></table></div></div>`}
function reviews(){return `<div class="section-head"><div><div class="eyebrow">Social proof</div><h2>Reviews</h2></div></div><div style="display:grid;gap:10px">${state.reviews.map((r,i)=>{const p=state.products.find(x=>x.id===r.productId);return `<div class="review"><div class="review-head"><div><b>${esc(r.name)}</b><div class="muted">${esc(p?.name||r.productId)} · ${'★'.repeat(r.rating)}</div></div><button class="btn danger" onclick="deleteReview(${i})">Delete</button></div><p>${esc(r.text)}</p></div>`}).join('')||'<div class="form-section"><div class="muted">No reviews yet.</div></div>'}</div>`}
window.deleteReview=i=>{state.reviews.splice(i,1);save();renderBody()}
function searchPanel(){const entries=Object.entries(state.searches).sort((a,b)=>b[1]-a[1]);return `<div class="section-head"><div><div class="eyebrow">Discovery</div><h2>Search & barcode</h2></div></div><div class="form-section"><h4>Top searches</h4>${entries.length?`<div class="chips">${entries.slice(0,20).map(([q,n])=>`<span class="chip gold">${esc(q)} · ${n}</span>`).join('')}</div>`:'<p class="muted">Search analytics will appear here after customers search.</p>'}</div><div class="form-section"><h4>Barcode catalog</h4><div style="overflow:auto"><table class="table"><thead><tr><th>Barcode</th><th>Product</th><th>Stock</th></tr></thead><tbody>${state.products.map(p=>`<tr><td>${esc(p.barcode)}</td><td>${esc(p.name)}</td><td>${p.stock}</td></tr>`).join('')}</tbody></table></div><p class="admin-note">The storefront also accepts barcode values directly in the search field. Camera barcode scanning can be added when the browser exposes BarcodeDetector.</p></div>`}
function exportData(){const blob=new Blob([JSON.stringify(state,null,2)],{type:'application/json'});const a=document.createElement('a');a.href=URL.createObjectURL(blob);a.download='kryven-era-data.json';a.click()}
function exportOrders(){const head=['Order ID','Date','Customer','Phone','Address','Total','Payment','Status'];const rows=state.orders.map(o=>[o.id,o.createdAt,o.customer.name,o.customer.phone,`${o.customer.address}, ${o.customer.city}, ${o.customer.pincode}`,o.total,o.payment,o.status]);const csv=[head,...rows].map(r=>r.map(x=>`"${String(x??'').replace(/"/g,'""')}"`).join(',')).join('\n');const blob=new Blob([csv],{type:'text/csv'});const a=document.createElement('a');a.href=URL.createObjectURL(blob);a.download='kryven-era-orders.csv';a.click()}
window.exportData=exportData;window.exportOrders=exportOrders;
app();
