/* KRYVEN ERA customer authentication. Uses Supabase Auth; customer details are kept in Auth user metadata, not the public storefront catalogue. */
(()=>{'use strict';
const URL='https://iisezaptudifgwkjxnkh.supabase.co';
const KEY='sb_publishable_oGorfrDciMl6GGOllbTjfg_Sr3YzDsH';
const SESSION_KEY='kryven-era-auth-session-v1';
let mode='signin', busy=false;
const esc=s=>String(s??'').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[m]));
function getSession(){try{return JSON.parse(localStorage.getItem(SESSION_KEY)||'null')}catch{return null}}
function setSession(s){try{if(s)localStorage.setItem(SESSION_KEY,JSON.stringify(s));else localStorage.removeItem(SESSION_KEY)}catch{};window.dispatchEvent(new CustomEvent('ke:auth',{detail:{session:s||null}}));}
async function authReq(path,body,token=''){
 const r=await fetch(`${URL}/auth/v1/${path}`,{method:'POST',headers:{apikey:KEY,'Content-Type':'application/json',...(token?{Authorization:`Bearer ${token}`}:{})},body:JSON.stringify(body||{})});
 const d=await r.json().catch(()=>({}));if(!r.ok)throw new Error(d.msg||d.message||d.error_description||d.error||'Authentication failed. Please try again.');return d;
}
async function liveSession(){let s=getSession();if(!s?.access_token)return null;const exp=Number(s.expires_at||0);if(exp&&exp*1000<Date.now()+60000&&s.refresh_token){try{s=await authReq('token?grant_type=refresh_token',{refresh_token:s.refresh_token});if(s.expires_in&&!s.expires_at)s.expires_at=Math.floor(Date.now()/1000)+Number(s.expires_in);setSession(s)}catch{setSession(null);return null}}return s}
function user(){return getSession()?.user||null}
function token(){return getSession()?.access_token||''}
function saveLocalProfile(u){try{const k='kryven-era-state-v3',s=JSON.parse(localStorage.getItem(k)||'{}');s.profile=Object.assign({},s.profile||{}, {name:u?.user_metadata?.name||s.profile?.name||'',phone:u?.user_metadata?.phone||s.profile?.phone||'',email:u?.email||s.profile?.email||'',address:u?.user_metadata?.address||s.profile?.address||'',landmark:u?.user_metadata?.landmark||s.profile?.landmark||'',houseNumber:u?.user_metadata?.houseNumber||s.profile?.houseNumber||'',city:u?.user_metadata?.city||s.profile?.city||'',state:u?.user_metadata?.state||s.profile?.state||'',pincode:u?.user_metadata?.pincode||s.profile?.pincode||'',customerId:u?.id||s.profile?.customerId||''});s.account=Object.assign({},s.account||{}, {signedIn:!!u,consent:true,signedInAt:new Date().toISOString(),authUserId:u?.id||''});localStorage.setItem(k,JSON.stringify(s))}catch{}}
function notify(msg){const t=document.getElementById('toast');if(t){t.textContent=msg;t.classList.add('show');setTimeout(()=>t.classList.remove('show'),3200)}else alert(msg)}
function ensureOverlay(){let el=document.getElementById('keAuthOverlay');if(el)return el;el=document.createElement('div');el.id='keAuthOverlay';el.className='ke-auth-overlay';el.innerHTML=`<div class="ke-auth-panel" role="dialog" aria-modal="true" aria-labelledby="keAuthTitle"><button class="ke-auth-close" type="button" onclick="KEAuth.close()" aria-label="Close">×</button><div class="ke-auth-kicker">KRYVEN ERA / CUSTOMER ACCOUNT</div><h2 id="keAuthTitle">Enter your ERA.</h2><p class="ke-auth-sub">Save your details, access member prices and keep one-use rewards linked to your account.</p><div class="ke-auth-modes"><button type="button" id="keAuthSignInTab" onclick="KEAuth.setMode('signin')">SIGN IN</button><button type="button" id="keAuthSignUpTab" onclick="KEAuth.setMode('signup')">CREATE ACCOUNT</button></div><form id="keAuthForm"><div id="keAuthNameWrap" class="ke-auth-field"><label for="keAuthName">FULL NAME</label><input id="keAuthName" autocomplete="name" maxlength="100" placeholder="Your full name"></div><div id="keAuthPhoneWrap" class="ke-auth-field"><label for="keAuthPhone">MOBILE NUMBER</label><input id="keAuthPhone" inputmode="tel" autocomplete="tel" maxlength="14" placeholder="10-digit mobile number"></div><div class="ke-auth-field"><label for="keAuthEmail">EMAIL ADDRESS</label><input id="keAuthEmail" type="email" autocomplete="email" maxlength="120" required placeholder="you@example.com"></div><div class="ke-auth-field"><label for="keAuthPassword">PASSWORD</label><input id="keAuthPassword" type="password" autocomplete="current-password" minlength="8" required placeholder="At least 8 characters"></div><label id="keAuthConsentWrap" class="ke-auth-consent"><input id="keAuthConsent" type="checkbox"><span>I agree to the KRYVEN ERA privacy policy and account terms.</span></label><div id="keAuthMessage" class="ke-auth-message" role="status"></div><button id="keAuthSubmit" class="ke-auth-submit" type="submit">SIGN IN →</button></form><p class="ke-auth-foot">Never share your password or OTP. Sign-in may require email confirmation depending on account settings.</p></div>`;
 document.body.appendChild(el);el.addEventListener('click',e=>{if(e.target===el)close()});el.querySelector('#keAuthForm').addEventListener('submit',submit);return el}
function open(){const overlay=ensureOverlay();overlay.classList.add('show');if(user()){showProfile();return}setMode('signin');setTimeout(()=>document.getElementById('keAuthEmail')?.focus(),100)}
function close(){document.getElementById('keAuthOverlay')?.classList.remove('show')}
function setMode(next){mode=next==='signup'?'signup':'signin';const overlay=ensureOverlay();resetProfileModal();overlay.querySelector('#keAuthTitle').textContent=mode==='signup'?'Create your ERA account.':'Welcome back.';overlay.querySelector('#keAuthNameWrap').style.display=mode==='signup'?'':'none';overlay.querySelector('#keAuthPhoneWrap').style.display=mode==='signup'?'':'none';overlay.querySelector('#keAuthConsentWrap').style.display=mode==='signup'?'':'none';overlay.querySelector('#keAuthPassword').autocomplete=mode==='signup'?'new-password':'current-password';overlay.querySelector('#keAuthSubmit').textContent=mode==='signup'?'CREATE ACCOUNT →':'SIGN IN →';overlay.querySelector('#keAuthSignInTab').classList.toggle('active',mode==='signin');overlay.querySelector('#keAuthSignUpTab').classList.toggle('active',mode==='signup');overlay.querySelector('#keAuthMessage').textContent='';}
async function submit(e){e.preventDefault();if(busy)return;const overlay=ensureOverlay();const email=overlay.querySelector('#keAuthEmail').value.trim().toLowerCase(),password=overlay.querySelector('#keAuthPassword').value;const name=overlay.querySelector('#keAuthName').value.trim(),phone=overlay.querySelector('#keAuthPhone').value.replace(/\D/g,'').slice(-10);const message=overlay.querySelector('#keAuthMessage');
 if(!email||!/^\S+@\S+\.\S+$/.test(email)){message.textContent='Enter a valid email address.';return}if(password.length<8){message.textContent='Password must be at least 8 characters.';return}if(mode==='signup'&&(!name||!/^\d{10}$/.test(phone))){message.textContent='Enter your full name and a valid 10-digit mobile number.';return}if(mode==='signup'&&!overlay.querySelector('#keAuthConsent').checked){message.textContent='Please accept the account terms to continue.';return}
 busy=true;overlay.querySelector('#keAuthSubmit').disabled=true;message.textContent=mode==='signup'?'Creating your account…':'Signing in…';
 try{
  let data;if(mode==='signup'){data=await authReq('signup',{email,password,data:{name,phone}});if(!data.access_token){message.textContent='Account created. Check your email to confirm it, then use SIGN IN.';return}}
  else data=await authReq('token?grant_type=password',{email,password});
  if(data.expires_in&&!data.expires_at)data.expires_at=Math.floor(Date.now()/1000)+Number(data.expires_in);setSession(data);saveLocalProfile(data.user);message.textContent='Signed in successfully.';close();notify('KRYVEN ERA account connected.');if(window.location.pathname.endsWith('checkout.html')){window.dispatchEvent(new CustomEvent('ke:auth-updated'))}else if(location.pathname.endsWith('rewards.html'))setTimeout(()=>window.renderKryvenRewards?.(),80);else if(location.pathname.endsWith('membership.html'))setTimeout(()=>window.renderKryvenMembership?.(),80);else if(location.pathname.endsWith('coupons.html'))setTimeout(()=>window.renderKryvenCoupons?.(),80);else if(typeof window.render==='function')setTimeout(()=>window.render(),80);
 }catch(err){message.textContent=err.message||'Could not sign in. Check details and try again.'}finally{busy=false;overlay.querySelector('#keAuthSubmit').disabled=false}}
async function signOut(){const s=getSession();try{if(s?.access_token)await fetch(`${URL}/auth/v1/logout`,{method:'POST',headers:{apikey:KEY,Authorization:`Bearer ${s.access_token}`}})}catch{}setSession(null);saveLocalProfile(null);notify('Signed out.');close();if(typeof window.render==='function')window.render()}
function showProfile(){const overlay=ensureOverlay();overlay.querySelector('#keAuthTitle').textContent='Your ERA account';overlay.querySelector('#keAuthForm').style.display='none';overlay.querySelector('#keAuthMessage').textContent='';let profile=overlay.querySelector('#keAuthProfile');if(!profile){profile=document.createElement('div');profile.id='keAuthProfile';profile.className='ke-auth-profile';overlay.querySelector('#keAuthForm').after(profile)}const u=user();profile.innerHTML=`<div><span>EMAIL</span><b>${esc(u?.email||'')}</b></div><div><span>NAME</span><b>${esc(u?.user_metadata?.name||'Customer')}</b></div><div><span>MOBILE</span><b>${esc(u?.user_metadata?.phone||'')}</b></div><a href="membership.html">ERA PASS / MEMBERSHIP →</a><a href="rewards.html">SPIN THE ERA →</a><button class="ke-auth-submit" type="button" onclick="KEAuth.close();KEAuth.signOut()">SIGN OUT</button>`;profile.style.display='grid';overlay.querySelector('.ke-auth-modes').style.display='none';overlay.querySelector('.ke-auth-sub').textContent='Your one-time rewards and membership are tied to this account.';overlay.classList.add('show');}
function resetProfileModal(){const o=document.getElementById('keAuthOverlay');if(!o)return;o.querySelector('#keAuthForm').style.display='';o.querySelector('#keAuthProfile')?.remove();o.querySelector('.ke-auth-modes').style.display='';o.querySelector('.ke-auth-sub').textContent='Save your details, access member prices and keep one-use rewards linked to your account.'}
function accessToken(){return getSession()?.access_token||''}
async function authFetch(url,options={}){const s=await liveSession();if(!s?.access_token)throw new Error('Sign in to continue.');return fetch(url,{...options,headers:{...(options.headers||{}),Authorization:`Bearer ${s.access_token}`}})}
const api={open,close,signOut,setMode,session:getSession,user,accessToken,authFetch,liveSession,resetProfileModal,isSignedIn:()=>!!getSession()?.access_token};
window.KEAuth=api;window.openProfile=open;
window.addEventListener('ke:auth',e=>{if(e.detail?.session?.user)saveLocalProfile(e.detail.session.user)});
// Expose auth session snapshot to checkout without copying any private token into order metadata.
window.dispatchEvent(new CustomEvent('ke:auth-ready',{detail:{signedIn:api.isSignedIn()}}));
})();
