(()=>{
const STATE_KEY='kryven-era-state-v3';
const CART_KEY='kryven-era-cart-v2';
const DRAFT_KEY='kryven-era-checkout-draft-v1';
const SUPABASE_URL='https://iisezaptudifgwkjxnkh.supabase.co';
const SUPABASE_KEY='sb_publishable_oGorfrDciMl6GGOllbTjfg_Sr3YzDsH';
const SUPABASE_TABLE='Allow public order insert';
const SUPABASE_REST=`${SUPABASE_URL}/rest/v1/${encodeURIComponent(SUPABASE_TABLE)}`;
const fallback={products:[
{id:'KE001',name:'Kryven Era Logo Tee',price:1299,mrp:1999,images:['https://images.unsplash.com/photo-1521572163474-6864f9cf17ab?auto=format&fit=crop&w=800&q=85'],sizes:{S:true,M:true,L:true,XL:true,XXL:false},colors:['Black','White','Silver']},
{id:'KE002',name:'Kryven Signature Hoodie',price:2499,mrp:3199,images:['https://images.unsplash.com/photo-1556821840-3a63f95609a7?auto=format&fit=crop&w=800&q=85'],sizes:{S:true,M:true,L:true,XL:false,XXL:true},colors:['Black','Stone']},
{id:'KE003',name:'Kryven Era Cargo Pants',price:1999,mrp:2599,images:['https://images.unsplash.com/photo-1515886657613-9f3515b0c78f?auto=format&fit=crop&w=800&q=85'],sizes:{S:false,M:true,L:true,XL:true,XXL:true},colors:['Black','Graphite']}
]};
function readState(){let s={};try{s=JSON.parse(localStorage.getItem(STATE_KEY)||'{}')||{}}catch{};s.products=Array.isArray(s.products)&&s.products.length?s.products:fallback.products;s.cart=Array.isArray(s.cart)?s.cart:[];s.profile=Object.assign({name:'',email:'',phone:'',address:'',landmark:'',houseNumber:'',city:'',state:'',pincode:'',customerId:''},s.profile||{});s.settings=Object.assign({currency:'₹',shipping:0,brand:'KRYVEN ERA',payments:{cod:true}},s.settings||{});s.settings.payments=Object.assign({cod:true,codAdvancePercent:20},s.settings.payments||{});s.orders=Array.isArray(s.orders)?s.orders:[];return s}
let state=readState();
function saveState(){try{localStorage.setItem(STATE_KEY,JSON.stringify(state));localStorage.setItem(CART_KEY,JSON.stringify(state.cart))}catch{}}
function product(id){return state.products.find(p=>String(p.id)===String(id))||fallback.products.find(p=>String(p.id)===String(id))||null}
function num(v){if(typeof v==='number'&&Number.isFinite(v))return v;if(v===null||v===undefined)return 0;const n=Number(String(v).replace(/[^0-9.\-]/g,''));return Number.isFinite(n)?n:0}
function productUnitPrice(p,x={}){const candidates=[p?.price,p?.sellingPrice,p?.salePrice,p?.finalPrice,p?.discountedPrice,p?.unitPrice,p?.amount,x?.unitPrice,x?.price,x?.salePrice,x?.sellingPrice,x?.originalUnitPrice];for(const v of candidates){const n=num(v);if(n>0)return n}return 0}
function productName(p,x={}){return p?.name||x?.name||x?.title||x?.productName||x?.id||'Product'}
function productImage(p,x={}){return p?.images?.[0]||p?.image||x?.image||x?.imageUrl||''}
function money(n){return `${state.settings.currency||'₹'}${num(n).toLocaleString('en-IN',{maximumFractionDigits:2})}`}
function esc(v){return String(v??'').replace(/[&<>'"]/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[m]))}
function getCart(){try{const raw=localStorage.getItem(CART_KEY);if(raw!==null){const x=JSON.parse(raw);if(Array.isArray(x)){state.cart=x;return x}}}catch{};state.cart=Array.isArray(state.cart)?state.cart:[];return state.cart}
function offerActive(p){const o=p?.offer||{}, setting=state.settings?.offers||{};return !!o.enabled&&((o.type==='percent'&&setting.percent50?.enabled!==false)||(o.type==='bogo'&&setting.bogo?.enabled!==false))}
function linePrice(p,q,x={}){q=Math.max(1,num(q)||1);const unit=productUnitPrice(p,x);if(!unit)return 0;if(!offerActive(p))return unit*q;const o=p.offer||{};if(o.type==='percent'){const pct=Math.max(1,Math.min(100,num(o.percent)||50));return Math.round(unit*q*(1-pct/100))}if(o.type==='bogo')return unit*(q-Math.floor(q/2));return unit*q}
function pricing(){const cart=getCart();let subtotal=0,after=0;for(const x of cart){const p=product(x.id);const q=Math.max(1,num(x.qty)||1);const unit=productUnitPrice(p,x);if(!unit)continue;subtotal+=unit*q;after+=linePrice(p,q,x)}const discount=Math.max(0,subtotal-after);const shipping=num(state.settings.shipping);return{subtotal,discount,shipping,total:Math.max(0,after+shipping)}}
function customerId(){let id=state.profile.customerId||localStorage.getItem('kryven-era-customer-id')||'';if(!id){const seed=(state.profile.phone||state.profile.email||state.profile.name||'customer')+'|'+Date.now();let h=0;for(let i=0;i<seed.length;i++)h=((h<<5)-h)+seed.charCodeAt(i)|0;id='KE-C-'+Math.abs(h).toString(36).toUpperCase().slice(-7);localStorage.setItem('kryven-era-customer-id',id)}state.profile.customerId=id;return id}
function loadDraft(){try{return JSON.parse(localStorage.getItem(DRAFT_KEY)||'{}')||{}}catch{return {}}}
function saveDraft(fromForm=true){const q=loadDraft();if(fromForm){const ids=['coName','coPhone','coEmail','coAddress','coLandmark','coHouse','coCity','coState','coPin'];for(const id of ids){const el=document.getElementById(id);if(el)q[({coName:'name',coPhone:'phone',coEmail:'email',coAddress:'address',coLandmark:'landmark',coHouse:'houseNumber',coCity:'city',coState:'state',coPin:'pincode'})[id]]=el.value.trim()}}state.profile={...state.profile,...q,customerId:customerId()};try{localStorage.setItem(DRAFT_KEY,JSON.stringify(state.profile))}catch{};saveState()}
function toast(msg){let el=document.getElementById('flowToast');if(!el){el=document.createElement('div');el.id='flowToast';el.style.cssText='position:fixed;left:50%;bottom:22px;transform:translateX(-50%);z-index:500;background:#111512;color:#fff;padding:12px 16px;border-radius:999px;font:700 11px/1.2 Arial,sans-serif;box-shadow:0 12px 34px rgba(0,0,0,.2)';document.body.appendChild(el)}el.textContent=msg;clearTimeout(el._t);el._t=setTimeout(()=>el.remove(),2800)}
function orderId(){return 'KE-'+new Date().getFullYear()+'-'+Math.floor(100+Math.random()*900)+'-'+String(Date.now()).slice(-5)}
function normalizeCart(){let carts=[];try{const a=JSON.parse(localStorage.getItem(CART_KEY)||'null');if(Array.isArray(a))carts.push(a)}catch{};if(Array.isArray(state.cart)&&state.cart.length)carts.push(state.cart);const merged=[];for(const c of carts){for(const x of c||[]){if(!x||!x.id)continue;const q=Math.max(1,Number(x.qty||1));const key=String(x.id)+'|'+String(x.size||'')+'|'+String(x.color||'');const found=merged.find(y=>y._key===key);if(found)found.qty=Math.max(found.qty,q);else merged.push({...x,qty:q,_key:key})}}for(const x of merged)delete x._key;return merged}
function buildOrder(payment){const cart=normalizeCart();state.cart=cart;saveState();const items=cart.map(x=>{const pr=product(x.id);const unit=productUnitPrice(pr,x);const qty=Math.max(1,num(x.qty)||1);const line=linePrice(pr,qty,x)||unit*qty;return{...x,name:productName(pr,x),image:productImage(pr,x),lineTotal:num(line),originalUnitPrice:unit}}).filter(x=>x.originalUnitPrice>0&&x.lineTotal>=0);let subtotal=items.reduce((a,x)=>a+num(x.originalUnitPrice)*Math.max(1,num(x.qty)||1),0);let total=items.reduce((a,x)=>a+num(x.lineTotal),0);const shipping=num(state.settings.shipping);total=Math.max(0,total+shipping);const discount=Math.max(0,subtotal-(total-shipping));const p={subtotal,discount,shipping,total};return{id:orderId(),createdAt:new Date().toISOString(),customerId:customerId(),customer:{...state.profile},items,subtotal:p.subtotal,discount:p.discount,total:p.total,shipping:p.shipping,payment,status:payment==='cod'?'Placed':'Awaiting Payment Verification',paymentVerified:false,advancePaid:payment==='cod'?Math.round(p.total*Math.max(0,Math.min(100,num(state.settings.payments?.codAdvancePercent??20)))/100):p.total,remainingDue:payment==='cod'?Math.max(0,p.total-Math.round(p.total*Math.max(0,Math.min(100,num(state.settings.payments?.codAdvancePercent??20)))/100)):0}}
async function cloudSave(order){try{const controller=new AbortController();const timer=setTimeout(()=>controller.abort(),5000);const row={id:Number(`${Date.now()}${Math.floor(Math.random()*1000)}`),'Customer name':order.customer.name||'','Customer address':`${order.customer.houseNumber?order.customer.houseNumber+', ':''}${order.customer.address||''}${order.customer.landmark?', '+order.customer.landmark:''}, ${order.customer.city||''}, ${order.customer.state||''}, ${order.customer.pincode||''}`,'Product name':JSON.stringify(order),'Customer number':order.customer.phone||'','Product price':String(order.total||0),'Product size':order.items.map(x=>`${x.name} x${x.qty||1} ${x.size||''}`).join(' | ')};const r=await fetch(SUPABASE_REST,{method:'POST',headers:{apikey:SUPABASE_KEY,Authorization:`Bearer ${SUPABASE_KEY}`,'Content-Type':'application/json',Prefer:'return=minimal'},body:JSON.stringify(row),signal:controller.signal});clearTimeout(timer);return r.ok}catch{return false}}
function validate(){saveDraft(true);const req=[['coName','Full name'],['coPhone','Mobile number'],['coAddress','Full address'],['coLandmark','Landmark'],['coCity','City'],['coState','State'],['coPin','Pincode']];let ok=true;for(const [id,label] of req){const el=document.getElementById(id);el?.classList.remove('field-invalid');document.querySelector(`#err-${id}`)?.remove();if(!el?.value.trim()){ok=false;if(el){el.classList.add('field-invalid');const e=document.createElement('div');e.id=`err-${id}`;e.className='checkout-field-error';e.textContent=`${label} is required`;el.parentElement.appendChild(e)}}}const phone=(document.getElementById('coPhone')?.value||'').replace(/\D/g,'');if(phone&&!/^\d{10}$/.test(phone)){ok=false;const el=document.getElementById('coPhone');el.classList.add('field-invalid');const e=document.createElement('div');e.className='checkout-field-error';e.textContent='Enter a valid 10-digit mobile number';el.parentElement.appendChild(e)}const pin=document.getElementById('coPin')?.value.trim()||'';if(pin&&!/^\d{6}$/.test(pin)){ok=false;const el=document.getElementById('coPin');el.classList.add('field-invalid');const e=document.createElement('div');e.className='checkout-field-error';e.textContent='Enter a valid 6-digit pincode';el.parentElement.appendChild(e)}return ok}
function checkoutFieldHtml(id,label,placeholder,kind,value){
  if(kind==='textarea') return `<div class="checkout-field full"><label>${label}</label><textarea id="${id}" autocomplete="street-address" placeholder="${placeholder}">${esc(value||'')}</textarea></div>`;
  const type=kind==='email'?'type="email"':'type="text"';
  const inputMode=kind==='tel'?'inputmode="tel"':(id==='coPin'?'inputmode="numeric"':'');
  const autocomplete=kind==='tel'?'tel':(kind==='email'?'email':'off');
  return `<div class="checkout-field"><label>${label}</label><input id="${id}" ${type} ${inputMode} autocomplete="${autocomplete}" maxlength="${id==='coPin'?'6':''}" placeholder="${placeholder}" value="${esc(value||'')}"></div>`;
}
function checkoutHTML(){
  const cart=getCart(), p=pricing(), draft={...state.profile,...loadDraft()};
  const fields=[
    ['coName','FULL NAME *','Enter your full name','text',draft.name],
    ['coPhone','MOBILE NUMBER *','10-digit mobile number','tel',draft.phone],
    ['coEmail','EMAIL ID (Optional)','name@example.com','email',draft.email],
    ['coAddress','FULL ADDRESS *','House / street / area / locality','textarea',draft.address],
    ['coLandmark','LANDMARK *','Nearby landmark','text',draft.landmark],
    ['coHouse','HOUSE / BUILDING NUMBER (Optional)','Flat 402 / Building 7','text',draft.houseNumber],
    ['coCity','CITY *','City','text',draft.city],
    ['coState','STATE *','State','text',draft.state],
    ['coPin','PINCODE *','6-digit PIN','text',draft.pincode]
  ];
  return `<header class="header"><div class="container nav"><a class="logo" href="index.html"><img src="favicon.png" style="width:30px;height:30px;border-radius:50%" alt="KRYVEN ERA"><span class="logo-text">KRYVEN ERA<small>THE ERA OF UNCOMPROMISING STYLE</small></span></a><div class="nav-actions"><a class="icon-btn bag-btn" href="bag.html" aria-label="Bag"><svg width="18" height="18" viewBox="0 0 24 24" aria-hidden="true"><path d="M6.5 8.5h11l1 12h-13l1-12Z" fill="none" stroke="currentColor" stroke-width="1.8" stroke-linejoin="round"/><path d="M9 9V7a3 3 0 0 1 6 0v2" fill="none" stroke="currentColor" stroke-width="1.8" stroke-linecap="round"/></svg><span class="badge">${cart.reduce((a,x)=>a+Number(x.qty||1),0)||''}</span></a></div></div></header>
  <main class="container checkout-standalone"><a class="checkout-back" href="bag.html">← Back to bag</a><div class="page-title"><div class="eyebrow">KRYVEN ERA / SECURE CHECKOUT</div><h1>Complete your order.</h1><p class="muted">Your details are saved on this device and reused on future checkouts.</p></div><div class="checkout-shell"><div class="checkout-main">
  <section class="checkout-panel"><div class="checkout-panel-head"><div class="step"><span>01</span><div><h2>Customer details</h2><small>Required fields are marked *</small></div></div><small>Saved automatically</small></div><div class="checkout-fields">${fields.map(f=>checkoutFieldHtml(...f)).join('')}</div><div class="saved-note">✓ Once entered, your customer details stay saved here. You do not need to refill them when switching between COD and Online Payment.</div></section>
  <section class="checkout-panel"><div class="checkout-panel-head"><div class="step"><span>02</span><div><h2>Choose payment</h2><small>Select a payment method, then confirm your order.</small></div></div></div><div class="pay-choice-grid"><label class="pay-choice cod"><input type="radio" name="paymentChoice" value="cod" checked><span class="pay-choice-body"><b>Cash on Delivery</b><small>Pay when your order is delivered.</small></span></label><label class="pay-choice online"><input type="radio" name="paymentChoice" value="online" id="onlineChoice"><span class="pay-choice-body"><b>Online Payment</b><small>UPI · Card · Net Banking via Cashfree.</small></span></label></div><button class="btn primary" type="button" id="confirmOrderBtn" style="width:100%;margin-top:18px">CONFIRM ORDER →</button><div id="checkoutError" class="checkout-error"></div></section>
  </div><aside class="checkout-summary"><div class="kicker">ORDER SUMMARY</div><h2 style="margin:8px 0 4px;font:700 28px 'Playfair Display',serif">Ready for checkout.</h2>${cart.map(x=>{const pr=product(x.id),q=Math.max(1,Number(x.qty||1));return `<div class="checkout-item"><img src="${esc(pr?.images?.[0]||'')}" alt=""><div><b>${esc(pr?.name||x.id)}</b><small>${esc(x.color||'Black')} · Size ${esc(x.size||'—')} · Qty ${q}</small></div><strong>${money(linePrice(pr,q))}</strong></div>`}).join('')}<div class="checkout-lines"><div class="checkout-line"><span>Subtotal</span><b>${money(p.subtotal)}</b></div><div class="checkout-line"><span>Offer savings</span><b>−${money(p.discount)}</b></div><div class="checkout-line"><span>Shipping</span><b>${p.shipping?money(p.shipping):'FREE'}</b></div><div class="checkout-line total"><span>Total</span><b>${money(p.total)}</b></div></div><div class="muted" style="font-size:9px;line-height:1.6;margin-top:12px">Online payments are handled on the separate Cashfree payment page. Your secret key never goes into this page.</div></aside></div></main>`;
}

function bindCheckout(){for(const id of ['coName','coPhone','coEmail','coAddress','coLandmark','coHouse','coCity','coState','coPin'])document.getElementById(id)?.addEventListener('input',()=>saveDraft(true));const goOnline=()=>{
  if(!validate())return;
  let order=buildOrder('cashfree');
  order=rebuildPaymentOrder(order)||order;
  if(!Array.isArray(order.items)||!order.items.length||!(Number(order.total)>0)){
    const box=document.getElementById('checkoutError');
    if(box){box.textContent=`Unable to calculate the order total. Items found: ${Array.isArray(order?.items)?order.items.length:0}. Please refresh the checkout once and try again.`;box.className='checkout-error show';}
    return;
  }
  localStorage.setItem('kryven-cashfree-pending-order',JSON.stringify(order));
  location.href='payment.html';
};const placeCod=async()=>{if(!validate())return;const order=buildOrder('cod');localStorage.setItem('kryven-last-order',JSON.stringify(order));state.orders=[order,...state.orders];state.cart=[];saveState();document.getElementById('checkoutApp').innerHTML=`<header class="header"><div class="container nav"><a class="logo" href="index.html"><img src="favicon.png" style="width:30px;height:30px;border-radius:50%"><span class="logo-text">KRYVEN ERA<small>THE ERA OF UNCOMPROMISING STYLE</small></span></a></div></header><main class="container" style="padding:70px 0"><div class="checkout-panel" style="max-width:720px;margin:auto;text-align:center"><div class="eyebrow">ORDER CONFIRMED</div><h1 style="font:700 48px 'Playfair Display',serif;margin:12px 0">Thank you.</h1><p class="muted">Your COD order <b>${esc(order.id)}</b> has been placed with your saved customer details.</p><a class="btn primary" href="tracking.html" style="margin-top:18px">TRACK ORDER →</a></div></main>`;cloudSave(order).catch(()=>{});};document.getElementById('confirmOrderBtn')?.addEventListener('click',()=>{const selected=document.querySelector('input[name="paymentChoice"]:checked')?.value;if(selected==='online')goOnline();else placeCod();});}
function renderCheckout(){if(!getCart().length){document.getElementById('checkoutApp').innerHTML='<main class="container" style="padding:90px 0;text-align:center"><div class="checkout-panel"><h1 style="font:700 44px \'Playfair Display\',serif">Your bag is empty.</h1><a class="btn primary" href="shop.html" style="margin-top:16px">EXPLORE COLLECTION →</a></div></main>';return}document.getElementById('checkoutApp').innerHTML=checkoutHTML();bindCheckout()}
function loadCashfree(){return new Promise((resolve,reject)=>{if(typeof window.Cashfree==='function')return resolve(window.Cashfree);const s=document.createElement('script');s.src='https://sdk.cashfree.com/js/v3/cashfree.js';s.async=true;s.onload=()=>resolve(window.Cashfree);s.onerror=()=>reject(new Error('Cashfree SDK could not be loaded. Please check your connection.'));document.head.appendChild(s)})}
function rebuildPaymentOrder(raw){
  let order=raw&&typeof raw==='object'?{...raw}:null;
  const liveCart=normalizeCart();
  if(liveCart.length){
    const rebuilt=buildOrder('cashfree');
    if(rebuilt.items.length && rebuilt.total>0 && (!order||!Array.isArray(order.items)||!order.items.length||!(num(order.total)>0))) order=rebuilt;
  }
  if(!order)return null;
  const safeItems=Array.isArray(order.items)?order.items:[];
  let subtotal=0,total=0;
  for(const x of safeItems){
    const pr=product(x.id);
    const qty=Math.max(1,num(x.qty)||1);
    const unit=productUnitPrice(pr,x);
    const line=linePrice(pr,qty,x)||num(x.lineTotal)||unit*qty;
    if(unit>0)subtotal+=unit*qty;
    if(line>=0)total+=line;
  }
  const shipping=num(order.shipping);
  if(subtotal>0)order.subtotal=subtotal;
  if(total>0)order.total=Math.max(0,total+shipping);
  if(num(order.total)>0&&num(order.subtotal)>0)order.discount=Math.max(0,num(order.subtotal)-(num(order.total)-shipping));
  if(!num(order.total)){const rebuilt=buildOrder('cashfree');if(rebuilt.items.length&&rebuilt.total>0)order=rebuilt;}
  try{localStorage.setItem('kryven-cashfree-pending-order',JSON.stringify(order))}catch{}
  return order;
}
function paymentOrder(){try{return rebuildPaymentOrder(JSON.parse(localStorage.getItem('kryven-cashfree-pending-order')||'null'))}catch{return rebuildPaymentOrder(null)}}
function paymentHTML(order){const p=pricingForOrder(order);return `<header class="header"><div class="container nav"><a class="logo" href="checkout.html"><img src="favicon.png" style="width:30px;height:30px;border-radius:50%" alt="KRYVEN ERA"><span class="logo-text">KRYVEN ERA<small>SECURE ONLINE PAYMENT</small></span></a></div></header><main class="container payment-page"><a class="back-link" href="checkout.html">← Back to checkout</a><div class="payment-shell"><section class="payment-card"><div class="eyebrow">KRYVEN ERA / CASHFREE</div><h1>Complete payment securely.</h1><p class="muted">Your customer details have already been saved. You are now on the separate online payment page.</p><div class="payment-note">UPI, cards and net banking are handled by Cashfree. KRYVEN ERA does not receive or store your UPI PIN or card PIN.</div><button class="cashfree-button" id="cashfreeBtn">OPEN CASHFREE PAYMENT →</button><div id="paymentStatus" class="payment-status wait show">Preparing secure payment…</div><div class="secure-list"><div>✓ Server-created Cashfree payment session</div><div>✓ Secret key stays on the Vercel server</div><div>✓ Final payment status verified server-side</div></div></section><aside class="payment-summary"><div class="kicker">ORDER</div><div class="pay-items">${(order.items||[]).map(x=>`<div class="pay-item"><img src="${esc(x.image||'')}" alt=""><div><b>${esc(x.name||x.id)}</b><small>${esc(x.color||'Black')} · Size ${esc(x.size||'—')} · Qty ${Number(x.qty||1)}</small></div><strong>${money(x.lineTotal)}</strong></div>`).join('')}</div><div class="pay-lines"><div class="pay-line"><span>Subtotal</span><b>${money(order.subtotal)}</b></div><div class="pay-line"><span>Savings</span><b>−${money(order.discount||0)}</b></div><div class="pay-line"><span>Shipping</span><b>${order.shipping?money(order.shipping):'FREE'}</b></div><div class="pay-line total"><span>Total</span><b>${money(order.total)}</b></div></div><div class="pending-order">Customer: ${esc(order.customer?.name||'')}<br>Phone: ${esc(order.customer?.phone||'')}<br>Order ID: ${esc(order.id)}</div></aside></div></main>`}
function pricingForOrder(o){const total=Number(o?.total||0);const subtotal=Number(o?.subtotal||0);const shipping=Number(o?.shipping||0);return{subtotal,discount:Number(o?.discount||0),shipping,total}}
async function startPayment(order){const btn=document.getElementById('cashfreeBtn'),st=document.getElementById('paymentStatus');try{btn.disabled=true;st.className='payment-status wait show';st.textContent='Creating secure Cashfree session…';const resp=await fetch('/api/create-order',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({order_id:order.id,order_amount:order.total,customer:{customer_id:order.customerId,customer_name:order.customer?.name,customer_email:order.customer?.email||'',customer_phone:order.customer?.phone}})});const data=await resp.json().catch(()=>({}));if(!resp.ok||!data.payment_session_id){const detail=data?.details?.message||data?.details?.error_description||data?.details?.error||data?.details?.type||'';const diag=data?.diagnostic;const diagText=diag?` [mode=${diag.environment||'?'}; API=${diag.api_version||'?'}; ID=${diag.client_id_present?'yes':'no'}; secret=${diag.client_secret_present?'yes':'no'}]`:'';throw new Error((data?.error||(detail?`Cashfree: ${detail}`:'Cashfree payment session was not created'))+diagText);}st.textContent='Opening Cashfree…';const Factory=await loadCashfree();const cf=Factory({mode:data.cashfree_mode||'production'});const result=await cf.checkout({paymentSessionId:data.payment_session_id,redirectTarget:'_self'});if(result?.error)throw new Error(result.error.message||'Cashfree checkout could not open');}catch(e){console.error(e);btn.disabled=false;st.className='payment-status err show';st.textContent=e.message||'Payment could not be started';}}
async function verifyReturn(){const url=new URL(location.href),oid=url.searchParams.get('order_id'),returned=url.searchParams.get('cashfree_return');if(!returned||!oid)return false;const st=document.getElementById('paymentStatus');const btn=document.getElementById('cashfreeBtn');if(btn)btn.disabled=true;if(st){st.className='payment-status wait show';st.textContent='Verifying payment status…'}try{const r=await fetch('/api/status?orderId='+encodeURIComponent(oid),{cache:'no-store'}),d=await r.json().catch(()=>({}));if(d.paid){const order=paymentOrder();if(order){order.status='Placed';order.paymentVerified=true;order.paidAt=new Date().toISOString();state.orders=[order,...state.orders];state.cart=[];saveState();localStorage.removeItem('kryven-cashfree-pending-order');setTimeout(()=>{cloudSave(order).catch(()=>{});},0)}if(st){st.className='payment-status ok show';st.textContent='Payment successful. Your order is confirmed.'}if(btn)btn.remove();setTimeout(()=>{location.href='tracking.html'},1400)}else{if(st){st.className='payment-status err show';st.textContent=d.pending?'Payment is still pending. Please wait and try again.':'Payment was not completed. No order was confirmed.'}if(btn)btn.disabled=false}}catch(e){if(st){st.className='payment-status err show';st.textContent='Could not verify payment status. Please refresh and try again.'}if(btn)btn.disabled=false}return true}
function renderPayment(){const order=paymentOrder();if(!order){document.getElementById('paymentApp').innerHTML='<main class="container" style="padding:90px 0;text-align:center"><div class="payment-card"><h1 style="font:700 42px \'Playfair Display\',serif">No pending payment.</h1><a class="btn primary" href="checkout.html" style="margin-top:16px">BACK TO CHECKOUT →</a></div></main>';return}document.getElementById('paymentApp').innerHTML=paymentHTML(order);document.getElementById('cashfreeBtn').addEventListener('click',()=>startPayment(order));verifyReturn();setTimeout(()=>{if(!new URL(location.href).searchParams.has('cashfree_return'))startPayment(order)},80);}
if(document.body.dataset.page==='checkout-standalone')renderCheckout();else if(document.body.dataset.page==='payment-standalone')renderPayment();
})();