const get=(k,d)=>{try{return JSON.parse(localStorage.getItem(k))??d}catch{return d}};
const set=(k,v)=>localStorage.setItem(k,JSON.stringify(v));
async function products(){try{return await (await fetch("products.json",{cache:"no-store"})).json()}catch{return[]}}
function money(n){return "₹"+Number(n).toLocaleString("en-IN")}
function updateBadges(){const c=get("ke_cart",[]),w=get("ke_wish",[]);document.querySelectorAll("[data-cart]").forEach(x=>x.textContent=c.reduce((a,b)=>a+(b.qty||1),0));document.querySelectorAll("[data-wish]").forEach(x=>x.textContent=w.length)}
function toast(t){const x=document.querySelector(".toast");if(x){x.textContent=t;x.style.display="block";clearTimeout(window._toast);window._toast=setTimeout(()=>x.style.display="none",1800)}}
function esc(v){return String(v??"").replace(/[&<>\"]/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;'}[m]))}
function card(p){const disc=p.mrp?Math.round((1-p.price/p.mrp)*100):0;const w=get("ke_wish",[]);return `<article class="card"><a href="product.html?id=${encodeURIComponent(p.id)}"><img src="${p.images[0]}" alt="${esc(p.name)}"></a><div class="card-body"><a href="product.html?id=${encodeURIComponent(p.id)}"><h3>${esc(p.name)}</h3></a><div class="rating">★ ${p.rating} (${p.reviews})</div><div class="price">${money(p.price)} <span class="old">${money(p.mrp)}</span><span class="discount">${disc}% off</span></div><p class="muted">${esc(p.fit)} · ${esc(p.color)}</p><button class="btn" onclick='addCart("${p.id}");return false'>ADD TO BAG</button><button class="btn" onclick='wish("${p.id}");return false'>${w.includes(p.id)?"♥":"♡"}</button></div></article>`}

async function render(){
 updateBadges();
 const ps=await products();
 let grid=document.querySelector("[data-products]")||document.querySelector("[data-listing]");
 if(grid){const q=new URLSearchParams(location.search).get("q");const list=q?ps.filter(p=>(p.name+" "+p.fit+" "+p.color).toLowerCase().includes(q.toLowerCase())):ps;grid.innerHTML=list.map(card).join("")||"<p>No products found.</p>"}

 let root=document.querySelector("#product-root");
 if(root){
  const p=ps.find(x=>x.id===new URLSearchParams(location.search).get("id"))||ps[0];
  if(p){
   window.currentProduct=p;
   window.selectedSize="M";
   root.innerHTML=`<div class="product-detail"><div class="gallery-wrap"><div class="gallery-stage"><img id="mainpic" class="gallery-main" src="${p.images[0]}" alt="${esc(p.name)}"></div><div class="thumbs">${p.images.map((i,idx)=>`<img class="gallery-thumb ${idx===0?"active":""}" src="${i}" data-gallery-index="${idx}" onclick="setGalleryImage(${idx})" alt="angle ${idx+1}">`).join("")}</div><div class="gallery-swipe-hint">← Swipe photo →</div></div><div class="product-info"><div class="eyebrow">KRYVEN ERA / FASHION</div><h1>${esc(p.name)}</h1><div class="rating">★ ${p.rating} · ${p.reviews} ratings & reviews</div><h2>${money(p.price)} <span class="old">${money(p.mrp)}</span> <span class="discount">${Math.round((1-p.price/p.mrp)*100)}% off</span></h2><p>Premium Kryven Era T-shirt with ${esc(p.fit.toLowerCase())} fit in ${esc(p.color.toLowerCase())}. Built for a clean luxury streetwear look.</p><div class="offer"><b>Available Offers</b><br>Special offer on selected products · Free standard delivery.</div><b>SELECT SIZE</b><div class="sizes">${["S","M","L","XL"].map(s=>`<button type="button" class="size ${s==="M"?"active":""}" onclick="selectSize(this,'${s}')">${s}</button>`).join("")}</div><div class="colour-choice"><b>COLOUR</b><div class="selected-colour"><span class="colour-dot" style="background:${colourHex(p.color)}"></span>${esc(p.color)}</div></div><p><b>Delivery</b><br>Enter your address at checkout to continue.</p><div class="buybar"><button class="btn" onclick='addCart("${p.id}",window.selectedSize)'>ADD TO BAG</button><button class="btn" onclick='addCart("${p.id}",window.selectedSize);location.href="checkout.html"'>BUY NOW</button></div></div></div><div class="panel detail-section"><h2>Product Highlights</h2><div class="highlights"><div class="highlight">Premium fabric</div><div class="highlight">${esc(p.fit)} fit</div><div class="highlight">Multiple sizes</div><div class="highlight">Kryven Era design</div></div></div><div class="panel detail-section"><h2>360° View</h2><p class="muted">Drag the shirt left or right to rotate it.</p><div class="viewer360" id="viewer360"><div class="shirt360" id="shirt360"></div></div><div class="viewer-help">Touch-drag on mobile · Mouse-drag on desktop</div></div><div class="panel detail-section"><h2>Ratings & Reviews</h2><div class="review">★ ${p.rating} — ${p.reviews} customer ratings</div><div class="review">Verified-style demo review: “Premium look and comfortable fit.”</div></div><div class="similar"><div class="section"><h2>Similar Products</h2></div><div class="products">${ps.filter(x=>x.id!==p.id).slice(0,4).map(card).join("")}</div></div>`;
   initGallery(p.images);
   init360();
  }
 }

 let cr=document.querySelector("#cart-root");
 if(cr){const c=get("ke_cart",[]);if(!c.length){cr.innerHTML="<div class='panel'><h2>Your bag is empty</h2><a class='btn' href='products.html'>SHOP NOW</a></div>"}else{let total=c.reduce((s,i)=>s+(ps.find(p=>p.id===i.id)?.price||0)*(i.qty||1),0);cr.innerHTML=c.map((i,idx)=>{const p=ps.find(x=>x.id===i.id);return p?`<div class="panel order-card"><div><b>${esc(p.name)}</b><p class="muted">${money(p.price)} × ${i.qty||1}</p><p class="item-meta"><b>Size:</b> ${esc(i.size||"M")} &nbsp; <b>Colour:</b> ${esc(i.color||p.color)}</p></div><button class="btn" onclick='removeCart("${p.id}",${idx})'>REMOVE</button></div>`:""}).join("")+`<div class="panel"><h2>Total: ${money(total)}</h2><a class="btn" href="checkout.html">PROCEED TO CHECKOUT</a></div>`}}

 let wr=document.querySelector("#wishlist-root");if(wr){const w=get("ke_wish",[]);wr.innerHTML=ps.filter(p=>w.includes(p.id)).map(card).join("")||"<div class='panel'><h2>Your wishlist is empty</h2><a class='btn' href='products.html'>EXPLORE PRODUCTS</a></div>"}
 let or=document.querySelector("#orders-root");if(or){const o=get("ke_orders",[]);or.innerHTML=o.map(x=>`<div class="panel order-card"><div><b>Order ${esc(x.id)}</b>${(x.itemDetails||[]).map(i=>`<p>${esc(i.name)} · Qty ${i.qty||1} · Size ${esc(i.size||"M")} · Colour ${esc(i.color||"")}</p>`).join("")}<p>${esc(x.name)} · ${esc(x.phone)}</p><p>${esc(x.address)}, ${esc(x.city)}, ${esc(x.state)} - ${esc(x.pincode)}</p><small>Placed: ${esc(x.date)}</small></div><span class="status">ORDER PLACED</span></div>`).join("")||"<div class='panel'><h2>No orders yet</h2><a class='btn' href='products.html'>START SHOPPING</a></div>"}
 let form=document.querySelector("#checkout-form");if(form){const prof=get("ke_profile",{});["name","phone","email","address","pincode","city","state"].forEach(k=>{const e=form.querySelector("[name='"+k+"']");if(e)e.value=prof[k]||""});renderCheckoutItems(ps)}
 let acc=document.querySelector("#account-form");if(acc){const prof=get("ke_profile",{});["name","phone","email","address","pincode","city","state"].forEach(k=>{const e=acc.querySelector("[name='"+k+"']");if(e)e.value=prof[k]||""})}
}

function colourHex(c){return ({Black:'#111',White:'#f5f5f5',Silver:'#aeb4bc',Red:'#a11',Blue:'#163a63',Yellow:'#d6b400'}[c]||'#888')}
function addCart(id,sizeOverride){let c=get("ke_cart",[]),p=(window.currentProduct&&window.currentProduct.id===id)?window.currentProduct:null;let size=sizeOverride||"M";let color=p?.color||null;let i=c.find(x=>x.id===id&&x.size===size&&(!color||x.color===color));if(i)i.qty++;else c.push({id,qty:1,size,color:color||undefined});set("ke_cart",c);updateBadges();toast("Added to Bag")}
function removeCart(id,idx){let c=get("ke_cart",[]);if(Number.isInteger(idx))c.splice(idx,1);else c=c.filter(x=>x.id!==id);set("ke_cart",c);render()}
function wish(id){let w=get("ke_wish",[]);w=w.includes(id)?w.filter(x=>x!==id):[...w,id];set("ke_wish",w);updateBadges();toast(w.includes(id)?"Added to Wishlist":"Removed from Wishlist");render()}
function selectSize(el,size){document.querySelectorAll(".size").forEach(x=>x.classList.remove("active"));el.classList.add("active");window.selectedSize=size}
function initGallery(images){
 const stage=document.querySelector(".gallery-stage"),img=document.getElementById("mainpic");
 if(!stage||!img||!images?.length)return;
 window._galleryImages=images;window._galleryIndex=0;
 let startX=0,startY=0,tracking=false;
 const show=(idx)=>{window._galleryIndex=(idx+images.length)%images.length;img.src=images[window._galleryIndex];document.querySelectorAll(".gallery-thumb").forEach((t,i)=>t.classList.toggle("active",i===window._galleryIndex));};
 window.setGalleryImage=show;
 stage.addEventListener("touchstart",e=>{if(!e.touches?.length)return;startX=e.touches[0].clientX;startY=e.touches[0].clientY;tracking=true},{passive:true});
 stage.addEventListener("touchend",e=>{if(!tracking||!e.changedTouches?.length)return;tracking=false;const dx=e.changedTouches[0].clientX-startX,dy=e.changedTouches[0].clientY-startY;if(Math.abs(dx)>45&&Math.abs(dx)>Math.abs(dy)*1.15){show(window._galleryIndex+(dx<0?1:-1));}}, {passive:true});
 let down=false,mouseX=0;
 stage.addEventListener("mousedown",e=>{down=true;mouseX=e.clientX;stage.classList.add("dragging")});
 window.addEventListener("mouseup",e=>{if(!down)return;down=false;stage.classList.remove("dragging");const dx=e.clientX-mouseX;if(Math.abs(dx)>55)show(window._galleryIndex+(dx<0?1:-1));});
}
function init360(){const v=document.getElementById("viewer360"),s=document.getElementById("shirt360");if(!v||!s)return;let down=false,last=0,rot=0;const move=x=>{if(!down)return;rot+=(x-last)*1.1;last=x;s.style.transform=`rotateY(${rot}deg)`};v.addEventListener("pointerdown",e=>{down=true;last=e.clientX;v.setPointerCapture(e.pointerId);s.style.cursor="grabbing"});v.addEventListener("pointermove",e=>move(e.clientX));v.addEventListener("pointerup",()=>{down=false;s.style.cursor="grab"});v.addEventListener("pointercancel",()=>down=false)}
function saveProfile(){const f=document.querySelector("#account-form");if(!f)return;const fd=new FormData(f),d={};["name","phone","email","address","pincode","city","state"].forEach(k=>d[k]=(fd.get(k)||"").toString().trim());set("ke_profile",d);toast("Account details saved")}
function renderCheckoutItems(ps){const box=document.querySelector("#checkout-items"),c=get("ke_cart",[]);if(!box)return;if(!c.length){box.innerHTML="<div class='checkout-empty'>Your bag is empty. <a href='products.html'>Shop products</a></div>";return}let total=0;box.innerHTML=`<h2 class="checkout-heading">Order Summary</h2>`+c.map((i,idx)=>{const p=ps.find(x=>x.id===i.id);if(!p)return"";total+=p.price*(i.qty||1);return `<div class="checkout-item"><img src="${p.images[0]}" alt="${esc(p.name)}"><div class="checkout-item-info"><b>${esc(p.name)}</b><div class="checkout-price">${money(p.price)} × ${i.qty||1}</div><div class="checkout-options"><label>SIZE <select onchange="updateCartOption(${idx},'size',this.value)">${["S","M","L","XL"].map(s=>`<option ${s===(i.size||"M")?"selected":""}>${s}</option>`).join("")}</select></label><label>COLOUR <span class="checkout-color"><i class="colour-dot" style="background:${colourHex(p.color)}"></i>${esc(p.color)}</span></label></div></div></div>`}).join("")+`<div class="checkout-total">Total <b>${money(total)}</b></div>`}
function updateCartOption(index,key,value){let c=get("ke_cart",[]);if(!c[index])return;c[index][key]=value;set("ke_cart",c);toast(key.toUpperCase()+" updated");render().then(()=>{const box=document.querySelector('#checkout-items');if(box)products().then(renderCheckoutItems)})}
function upiSuccessSound(){try{const C=window.AudioContext||window.webkitAudioContext;if(!C)return;const c=new C(),o=c.createOscillator(),g=c.createGain();o.type="sine";o.frequency.setValueAtTime(880,c.currentTime);o.frequency.setValueAtTime(1174,c.currentTime+.09);o.frequency.setValueAtTime(1568,c.currentTime+.18);g.gain.setValueAtTime(.0001,c.currentTime);g.gain.exponentialRampToValueAtTime(.18,c.currentTime+.02);g.gain.exponentialRampToValueAtTime(.0001,c.currentTime+.42);o.connect(g).connect(c.destination);o.start();o.stop(c.currentTime+.45)}catch(e){}}
document.addEventListener("submit",e=>{if(e.target.id==="checkout-form"){e.preventDefault();const f=new FormData(e.target),cart=get("ke_cart",[]);if(!cart.length){toast("Your bag is empty");return}const itemDetails=cart.map(x=>{const p=window._checkoutProducts?.find(p=>p.id===x.id);return {id:x.id,name:p?.name||x.id,qty:x.qty||1,size:x.size||"M",color:x.color||p?.color||""}});const order={id:"KE"+Date.now().toString().slice(-8),name:f.get("name"),phone:f.get("phone"),email:f.get("email"),address:f.get("address"),pincode:f.get("pincode"),city:f.get("city"),state:f.get("state"),items:itemDetails.map(x=>`${x.name} (${x.size}, ${x.color})`).join(", "),itemDetails,date:new Date().toLocaleString(),payment:"UPI / Payment success-style demo"};set("ke_profile",{name:order.name,phone:order.phone,email:order.email,address:order.address,pincode:order.pincode,city:order.city,state:order.state});set("ke_orders",[order,...get("ke_orders",[])]);set("ke_cart",[]);const no=document.querySelector("#order-no");if(no)no.textContent=order.id;const s=document.querySelector("#success");if(s)s.style.display="block";e.target.style.display="none";upiSuccessSound();toast("Order placed successfully")}})

async function initSearch(){const wrap=document.querySelector('.search-wrap'),input=document.getElementById('site-search'),box=document.getElementById('search-suggestions');if(!wrap||!input||!box)return;let all=[];const draw=(q='')=>{const term=q.trim().toLowerCase();const list=all.filter(p=>!term||(p.name+' '+p.fit+' '+p.color).toLowerCase().includes(term));box.innerHTML=list.map(p=>`<a class="search-suggestion" href="product.html?id=${encodeURIComponent(p.id)}">${esc(p.name)}</a>`).join('')||'<div class="search-suggestion" style="cursor:default;color:#777">No matching T-shirt</div>';box.classList.add('show')};products().then(ps=>{all=ps||[]});input.addEventListener('focus',()=>draw(input.value));input.addEventListener('input',()=>draw(input.value));document.addEventListener('click',e=>{if(!wrap.contains(e.target))box.classList.remove('show')});let lastY=window.scrollY||0,ticking=false;const onScroll=()=>{const y=window.scrollY||0;if(y>lastY+6&&y>70){wrap.classList.add('search-hidden');wrap.classList.remove('search-visible');box.classList.remove('show')}else if(y<lastY-6){wrap.classList.remove('search-hidden');wrap.classList.add('search-visible')}lastY=y;ticking=false};window.addEventListener('scroll',()=>{if(!ticking){requestAnimationFrame(onScroll);ticking=true}},{passive:true})}
function removeFloatingSearchWidget(){document.querySelectorAll('[data-floating-search],.floating-search,.floating-search-button').forEach(e=>e.remove())}
document.addEventListener("DOMContentLoaded",()=>{initSearch();removeFloatingSearchWidget();products().then(ps=>window._checkoutProducts=ps);render()})
