'use client';
import {Canvas,useFrame} from '@react-three/fiber';
import {Float,Environment,OrbitControls,Text} from '@react-three/drei';
import {useRef} from 'react';
import * as THREE from 'three';
function ChromeMark(){const ref=useRef<THREE.Group>(null);useFrame((_,d)=>{if(ref.current){ref.current.rotation.y+=d*.28;ref.current.rotation.x=Math.sin(performance.now()*.0004)*.12}});return <group ref={ref}><Float speed={2} rotationIntensity={.35} floatIntensity={1}><mesh><torusGeometry args={[1.15,.12,24,96]}/><meshStandardMaterial metalness={1} roughness={.18} color="#e8e8e8"/></mesh><mesh rotation={[Math.PI/2,0,0]}><torusGeometry args={[.72,.08,24,64]}/><meshStandardMaterial metalness={1} roughness={.12} color="#ff0033" emissive="#ff0033" emissiveIntensity={1.8}/></mesh></Float></group>}
function Particles(){const ref=useRef<THREE.Points>(null);const count=700;const pos=new Float32Array(count*3);for(let i=0;i<count;i++){pos[i*3]=(Math.random()-.5)*18;pos[i*3+1]=(Math.random()-.5)*12;pos[i*3+2]=(Math.random()-.5)*12}useFrame((_,d)=>{if(ref.current){ref.current.rotation.y+=d*.025;ref.current.rotation.x+=d*.008}});return <points ref={ref}><bufferGeometry><bufferAttribute attach="attributes-position" count={count} array={pos} itemSize={3}/></bufferGeometry><pointsMaterial color="#c0c0c0" size={.018} transparent opacity={.55}/></points>}
export default function ThreeScene({label=false}:{label?:boolean}){return <div className="absolute inset-0"><Canvas camera={{position:[0,0,6],fov:48}}><ambientLight intensity={.35}/><pointLight position={[3,2,5]} color="#ff0033" intensity={18}/><pointLight position={[-4,1,2]} color="#e8e8e8" intensity={10}/><Particles/><ChromeMark/>{label&&<Text position={[0,-2.2,0]} fontSize={.24} letterSpacing={.2} color="#c0c0c0" anchorX="center">KRYVEN ERA</Text>}<Environment preset="city"/></Canvas></div>}
export function Product3D(){return <div className="h-[360px] overflow-hidden rounded-3xl border border-white/10 bg-white/[.025]"><Canvas camera={{position:[0,0,4.5],fov:45}}><ambientLight intensity={.7}/><spotLight position={[4,4,5]} color="#ff0033" intensity={25}/><spotLight position={[-4,2,3]} color="#e8e8e8" intensity={18}/><Float speed={2} rotationIntensity={.4} floatIntensity={.8}><mesh rotation={[0,.3,0]}><boxGeometry args={[2.5,.35,2.8]}/><meshPhysicalMaterial color="#111" metalness={.65} roughness={.25} clearcoat={1}/></mesh><mesh position={[0,.35,0]}><boxGeometry args={[2.1,.12,2.35]}/><meshPhysicalMaterial color="#c0c0c0" metalness={1} roughness={.12}/></mesh></Float><OrbitControls enableZoom={false}/><Environment preset="city"/></Canvas></div>}
